"""GeneratedDocument model — outbound legal documents produced by the firm.

System requirement #3, slice 2: records each escrito/demanda the firm GENERATES
(as opposed to ``Document``, which tracks documents DOWNLOADED from PJUD). One
row per successful (or attempted) generation, with provenance (which lawyer,
which side) and a content-addressable ``storage_key`` into the storage backend.
"""

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import relationship

from app.core.database import Base


class GeneratedDocument(Base):
    """A legal document generated by the firm for a given case."""

    __tablename__ = "generated_documents"

    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(Integer, ForeignKey("cases.id"), nullable=False, index=True)

    document_type = Column(String(50), nullable=False)  # e.g. "escrito_oposicion"

    # Rendered artifact metadata
    filename = Column(String(255), nullable=True)
    content_type = Column(String(100), nullable=True)
    size_bytes = Column(BigInteger, nullable=True)
    storage_key = Column(String(512), nullable=True)  # storage URI returned by backend

    # Lifecycle: "stored" (bytes persisted) | "failed" (persistence hiccup)
    status = Column(String(20), nullable=False, server_default="stored")

    # Provenance — who acted and which side the firm was on at generation time
    generated_by_rut = Column(String(20), nullable=True)
    generated_by_name = Column(String(255), nullable=True)
    firm_side = Column(String(20), nullable=True)  # demandado | desconocido

    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    case = relationship("Case", back_populates="generated_documents")
